- .drone.yml
- .eslintrc
- .kube.dev.yaml
- .npmrc
- Dockerfile
- config.js
- index.js
- lib/api.js
- lib/can.js
- lib/error-handler.js
- package-lock.json
- package.json
- test/.eslintrc
- test/helpers/user-wrapper.js
- test/index.js
To check the permissions of a task:
```
GET /:taskid?params
```
Then the user (as authenticated by keycloak) will have their permissions interrogated to check if they have the roles as specified by the `permissions` config.
> First implementation of permissions API

- package-lock.json
- package.json
This allows us to load the api tools without all the excess UI things too.
> Update to latest service version

- config.js
- lib/can.js
- test/index.js
Also remove the unnecessary depth of structure in the config.
> Add permissions for SoP amendments

- test/index.spec.js
Instead of having lots of hard-coded uuids floating around.
> Set `id` as a variable

- config.js
- lib/utils/allowed.js
- test/index.spec.js
Resolves certain tasks for asru users as well as from establishment derived permissions.
> Add ASRU users to permissions matrix

- config.js
Currently using the same perms as Profiles.
> Add permissions for PILs

- config.js
* Added establishment pdf permissions for all asru users, and establishment admin/read user
* Added missing places list permissions, same as place reads
> Feature - est pdf permissions

- config.js
- lib/api.js
- lib/can.js
- lib/get-tasks.js
- lib/utils/allowed.js
- test/allowed.spec.js
- test/config.spec.js
* Added holdingEstablishment scope
* Updated allowed to perform async operations
* Lookup estId from pil and scope user
> PIL PDF perms

- config.js
restore previous permission for pil create - this was changed in error
> Bugfix - user can apply for own pil

- config.js
* Added permissions for pil.list
* Added permissions for establishment.licenceFees
> Feature - billing

- config.js
This will allow us to ship some initial functionality to production without exposing it to external users.
This can and will change in due course once it's been tested.
> Disable billing permission for any external users

- config.js
* Added permission for transferring a PPL to a new establishment
> Feature - ppl transfer

- lib/utils/allowed.js
- package-lock.json
- package.json
- test/allowed.spec.js
* we dont need all the data, just get the bit we care about
* installed objection to use ref
> Bugfix - only load what we need

- config.js
* Added pil review permission - NTCO
> Feature - PIL review

- config.js
- lib/utils/allowed.js
- package-lock.json
- package.json
- test/allowed.spec.js
* added project collaborator check to check if user is a collaborator
* added collaborator check to project read and projectVersion read
~wip until https://github.com/UKHomeOffice/asl-schema/pull/295~
> Feature - add project collaborators

- lib/utils/allowed.js
- test/allowed.spec.js
* Added additional check to make sure collaborator is still associated with the project establishment
> Bugfix - check collaborator at establishment

- config.js
* Added project.endorse permission - holding establishment admin
> Feature - project endorse permission

- config.js
- package-lock.json
This simplifies the code for the API, which currently reproduces this logic in code.
> Add permission for global profile

- .drone-1.0.yml
- config.js
- lib/utils/allowed.js
- package-lock.json
- package.json
- test/allowed.spec.js
- test/helpers/db.js
* Added new permission for additional est viewing a proj
* Updated collabs permission to include additional ests
> Feature - additional availability

- lib/can.js
- lib/get-tasks.js
- package-lock.json
- package.json
- test/allowed.spec.js
- test/index.spec.js
If a non-ASRU user has not verfied their email address then all permissions should return false.
> Disable all permissions for unverified user

- lib/utils/allowed.js
- package-lock.json
- package.json
- test/allowed.spec.js
Check the establishment parameter in the call, and ensure that it corresponds to the establishment with AA and where the user holds a role.
> Only allow Additional Availability access if scoped to the correct establishment

- config.js
- lib/utils/allowed.js
> Feature - RA

- config.js
- lib/utils/allowed.js
- package-lock.json
- package.json
* added collab:edit user to project edit
* added collab:edit user to training read
* added new project:submit permission
> Feature - collab perms

- config.js
Where previously only an licensing officer could do a thing, swap that out for an inspector
> Swap licensing permissions for inspector

- config.js
- package-lock.json
- package.json
- test/helpers/db.js
Also added a permission for PIL revoke for consistency (it was using `pil.update` previously see https://github.com/UKHomeOffice/asl-pages/pull/1499/files#diff-4ab69e1ad9ab590fa026e8e261e41d0e2a24d04a7710a11276d92bd074623506L18)
> Add permissions for suspend / reinstate licences
