UKHomeOffice/asl-permissions

.kube.dev.yaml
config.js
lib/api.js
lib/can.js
package-lock.json
package.json
test/index.js

Instead of loading roles and establishment associations from keycloak profile, look into the local database and get the establishment level permissions from there.
Note: inspector level permissions have been removed while we work out how they're going to work.

Refactor: permissions from profile

---

lib/can.js
lib/get-tasks.js
lib/utils/allowed.js

The parameters for the `allowed` function had been destructured to the extent of a) having convoluted names - e.g. `userRole`, `userId`, and b) being occasionally meaningless without context - e.g. `id` for profile id.
Add some structure to the arguments back so that there are three arguments: the task at hand, the user making the request, and the parameters of the request subject.
This allows context for variables like `id` - the id of the request subject.

Refactor function arguments for `allowed` method

---

lib/get-tasks.js
test/index.spec.js

Certain permissions are not acquired by virtue of a user being a member of a particular establishment (in particular internal users with global permissions) and so need to be defined without being scoped beneath a particular establishment.

Add support for non-establishment scoped permissions

---

lib/utils/allowed.js
test/allowed.spec.js

The subject is not always defined - in particular when called by `getTasks`, which has no particular context, so allow it to be undefined without failing.

Set default values for user and subject params in `allowed`

---

lib/api.js
lib/get-tasks.js
test/index.spec.js

This makes it consistent with the response for a particular task

Throw 400 error from `getTasks` if there is no user

---

config.js

Some parts of the UI determine visibility of components by only checking for basic permissions, so navigation elements were being hidden that should have been visible.

Add basic permissions as well as advanced permissions for ASRU users

---

config.js
lib/api.js
lib/can.js
lib/error-handler.js
lib/utils/allowed.js
test/config.spec.js
test/index.spec.js

Adds a new permissions definition of `establishment:role:<type>` which allows users who hold the defined role to perform the relevant task.

Expand `profile.read.all` permissions to include NTCOs

---

lib/utils/allowed.js
test/allowed.spec.js

Some implementations are still passing a plain `id` parameter for calls to permissions. Allow that to be used in place of the `thingId` param if that is not defined.

Fall back to `id` param if `thingId` is not defined

---

lib/error-handler.js

This prevents BAU 403 errors being included in error monitoring searches that exclude 4xx errors.

Include error status in logs

---

lib/utils/allowed.js
test/allowed.spec.js

All the other things which accept a `thingId` param will fall back to `id`. Add this to `project:own` permissions as well.

Allow `project:own` permissions to fall back to `id` param

---

lib/utils/allowed.js
test/allowed.spec.js

This is required as reading a project version requires to holding establishment permission, it was just on a project level before

added holdingEst permission to projectVersion

---

lib/utils/allowed.js
test/allowed.spec.js

* query deleted models when checking permissions
* this is needed if a model is deleted but a permissions check is still run (discarding project amendments and deletion tasks)

Bugfix - query with deleted

---

lib/api.js
lib/can.js
lib/utils/allowed.js
test/allowed.spec.js

If one particular role in a set of permissions fails then don't fail the entire request, just log the error and return false.

Handle errors in permissions checks

---

lib/utils/allowed.js
test/index.spec.js

When a user has the "blocked" permission at an establishment, they should not be allowed to do anything at that establishment.
Other establishments should continue to function as normal.

Users are prevented from all actions at blocked establishment

---

README.md
config.js
lib/api.js
lib/cache.js
package-lock.json
package.json

Adds an optional caching middleware in front of API to prevent thrashing the database when under load.
Connects to a redis store if one is available but falls back to an in-memory store otherwise.

Add a cache layer to API

---

lib/cache.js

This means that the high-level establishment permissions will update instantly when accepting a new establishment invitations.
Since this sits behind an existing cache of the user profile it should have negligible performance impact.

Exclude allowed actions endpoint from cache

---

config.js

This needs to go after the UI changes below so that we don't expose the holding establishment name to users not at the holding establishment.
~https://github.com/UKHomeOffice/asl-pages/pull/885~

Non-holding admins, ntcos can now download PIL pdf

---

config.js

We use "create" for all the other models, co I've renamed "apply" for consistency.
Import is a new perm which is used to display the Apply / Import buttons at the top of the projects list. Without this the buttons won't render for non-admins because there's no profile context.

Create ppl perms for admins

---

lib/utils/allowed.js

When signing in as an ASRU user, the permissions service is throwing errors when evaluating `additionalEstablishment:admin` and `projectVersion:collaborator` permissions.
This is because it's trying to `findById` for an undefined id.

Prevent missing ids breaking queries

---

config.js

The `project.read` permission was set for these users, but not the version permission.
Add version level and RA level access for readonly users at additional establishments.

Fix project permissions for additional establishment readonly users

---

config.js

Configure this separately from `project.update` so that it's clear from the permissions config which users can complete ROPs.

Add permissions config for ROPs completion

---

config.js

This means that we can initially restrict ROPs for external users to only those projects where ASRU have created the initial return.

Split create and update permissions for ROPs

---

config.js

These are currently spready through the codebase as a series of `isLicensing` conditions, which makes them difficult to update.
Add the permissions here so that they can be managed in one place.

Add legacy stub permissions

---

config.js

We don't currently have any way for a returns analyst to view the ROP for a particular project.
They probably don't _need_ write access, but since there's no concept of read-only ROPs usage this will have to do.

Allow ROPs analysts to access individual ROPs

---

config.js

Condition reminders appear to licence holders, which can then be dismissed if no-longer relevant.
External users should only be able to dismiss their own reminders.

Add permission for handling reminders
